### ISSUE TITLE
Install VS Code extension to standalone PC

### ISSUE THREAD

**Issue by joeamnesiac** [AlessandroDelSole/VSCodeSuccinctly#1]
Hi Alessandro,

I'm trying to use your Ada plugin for VS Code, but I either work on a PC behind a company firewall or on a stand-alone PC (no internet connection). I was wondering if you could assist me in installing the extension, I see that I should be able to install it from a vsix file, but I can't seem to locate one.

Thanks,
Joe

**Comment by AlessandroDelSole** [comment]
Hi, thanks for your interest. This repository contains the source code for an upcoming eBook called Visual Studio Code Succinctly, so until the book is out I can't share much content. 

The ADA language extension can be downloaded from VS Code directly, but if you can't, please place the source code into one folder and follow these docs:

https://code.visualstudio.com/docs/customization/colorizer
https://code.visualstudio.com/docs/extensions/install-extension
